### ISSUE TITLE
有没有考虑增加一个关于vis功能的插件呢？

### ISSUE THREAD

**Issue by gangyahaidao** [mgbq/vue-permission#15]
作者你好，看见你在Charts图标部分集成了很多的插件，想问一下你有没有考虑直接做一个关于vis的插件，vis地址是 http://visjs.org/

下面是一些用vis实现的图形功能截图，看起来很nx：
![image](https://user-images.githubusercontent.com/25075558/44013373-bb8ee0e0-9ef7-11e8-98f9-f6d5f9a123c2.png)
地址;http://visjs.org/examples/graph3d/04_animation.html

这种网络拓扑图
![image](https://user-images.githubusercontent.com/25075558/44013400-de497c4e-9ef7-11e8-9b84-9864f608959f.png)
[http://visjs.org/examples/network/nodeStyles/images.html](http://visjs.org/examples/network/nodeStyles/images.html)

这个应该是目前其他vue框架没有的插件

**Comment by mgbq** [comment]
暂不考虑，欢迎大家 pull

**Comment by gangyahaidao** [comment]
原来用vis做过一些地图的显示，最近发现echarts比vis效果好很多
