### ISSUE TITLE
如何整合到花裤衩的框架

### ISSUE THREAD

**Issue by luoshiwei** [mgbq/vue-permission#16]
您好，看了您封装的框架，非常好，后悔没早看到，但是我们已经在用花裤衩的框架了，请问该怎么把您的框架整合进来？

**Comment by mgbq** [comment]
你好，你想要在侧边栏的上边加入logo，且这个logo不会随侧边栏滚动，本项目就是基于花裤衩基本模板上面开发的，就是封装一个logo组件而已，你看下源码，复制黏贴即可。

**Comment by luoshiwei** [comment]
恩，已经搞定了，感谢指导。
