### ISSUE TITLE
请问svg icon 怎么调整尺寸

### ISSUE THREAD

**Issue by snail-oniu** [mgbq/vue-permission#19]
仔细看了下 svg icon 在svg 的xml 中有 width 、height和 viewBox 两个参数可以调整svg本身的尺寸。但是在nx-admin中貌似是被限制了，14px * 14px  不能更改。从iconfont拿来的图标看起来整体都偏小，请问要svg icon的尺寸大小怎么调整？

**Comment by mgbq** [comment]
css覆盖 或者 !important
