### ISSUE TITLE
按钮权限现在是无效的

### ISSUE THREAD

**Issue by q4452542007** [mgbq/vue-permission#25]
作者你好，我不知道是我没有搞清楚还是现在按钮权限的功能没有加进去

**Comment by mgbq** [comment]
仔细看，切换不同的权限显示不同的按钮

**Comment by q4452542007** [comment]
找到了  我之前被误导  我切换过权限之后  去看了表格页面内的按钮  我发现没有任何改变   现在看见是v-permisison指令定义的了  谢谢
