### ISSUE TITLE
动画在IOS上没有效果

### ISSUE THREAD

**Issue by wangzhengliang** [mgbq/vue-permission#28]
动画在安卓手机上可以正确显示，但是用IOS手机的时候不会显示，是什么原因啊？

**Comment by mgbq** [comment]
请问是跳转动画还是？

**Comment by wlei24** [comment]
首屏loading动画ios上不生效，麻烦看看啥原因

**Comment by mgbq** [comment]
首屏动画在index.html页面，动画是css写的，不生效就是css不兼容呗
