### ISSUE TITLE
关于跨域请求

### ISSUE THREAD

**Issue by xupeihong** [mgbq/vue-permission#33]
如果关闭mock数据，请求后台数据接口在哪里配置？支持跨域

**Comment by xhk** [comment]
/utils/request.js 里面 这行：
config.headers['X-Token'] = getToken() // 让每个请求携带自定义token 请根据实际情况自行修改

**Comment by mgbq** [comment]
本地开发支持跨越在vue.config.js里面devServer对象里面配置 proxy ，线上用服务器代理（nginx）或者jsonp,或者后台项目接口配置cors跨域
