### ISSUE TITLE
关于权限

### ISSUE THREAD

**Issue by yanyueWorld** [mgbq/vue-permission#35]
动态菜单的加载是从router里面获取的，那么请问一下，您是事先将asyncRouterMap中的路由写死了，然后在通过后端判断role来获取对应的动态路由，可以这样理解么，因为项目前端人手不够，被迫来开发前端，对这块的理解还是不怎么到位，麻烦能说明下么

**Comment by mgbq** [comment]
目前是这样的，你也可以用后端返回给你的路由实现动态。

**Comment by yanyueWorld** [comment]
感谢，
 
------------------
严悦
西华大学
电话：13320674900；
邮箱：yanyuejust@qq.com；
Never try, Never konw.


 




------------------ 原始邮件 ------------------
发件人: "肖敏"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 上午8:55
收件人: "mgbq/nx-admin"<nx-admin@noreply.github.com>; 
抄送: "三旬过场，人走茶凉"<1361557116@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mgbq/nx-admin] 关于权限 (#35)




目前是这样的，你也可以用后端返回给你的路由实现动态。
 
&mdash;
