### ISSUE TITLE
nxAdmine Vue 中加载 Cesium 总是失败

### ISSUE THREAD

**Issue by marrain** [mgbq/vue-permission#38]
![image](https://user-images.githubusercontent.com/19423894/71711812-a8513b00-2e3d-11ea-90a0-22c405fda92a.png)

**Comment by mgbq** [comment]
Cesium 是？

**Comment by marrain** [comment]
您好！
    cesium是一个开源的3D Web库，最后确定是版本问题。














在 2020-01-08 14:11:08，"肖敏" <notifications@github.com> 写道：

Cesium 是？
