### ISSUE TITLE
过滤路由循环调用自身

### ISSUE THREAD

**Issue by IMMYz** [mgbq/vue-permission#4]
如果路由下还存在子路由，在过滤合适的路由的时候会重复递归调用本身，导致报错

**Comment by mgbq** [comment]
没听明白，能麻烦你详细举个例子么

**Comment by IMMYz** [comment]
你好，是这样的
我在加载路由中添加了一个三级路由
[cid:image002.png@01D4016C.310D06A0]
当test路由下只有子路由 ‘testChild1’的时候一切正常，
当我在‘testchild1’ 下新增一个子路由‘testChild2’后，访问一个没有匹配的路由浏览器会报错 不能正常显示404页面

[cid:image004.png@01D4016C.1D57B510]
应该是根据权限添加路由的部分反复调用自身太多，进入死循环导致的报错，这个报错是在有三级路由的情况下会出现



________________________________
发件人: 肖敏 <notifications@github.com>
发送时间: Friday, June 8, 2018 5:09:57 PM
收件人: mgbq/vue-permission
抄送: IMMYz; Author
主题: Re: [mgbq/vue-permission] 过滤路由循环调用自身 (#4)


没听明白，能麻烦你详细举个例子么

―

**Comment by mgbq** [comment]
你好，今天我特意试了下，并没有出现你说的情况
