### ISSUE TITLE
动态路由，菜单权限

### ISSUE THREAD

**Issue by WhiteSean** [mgbq/vue-permission#41]
一级菜单设置成roles: ['admin', 'editor']，二级菜单，某些权限只能是admin,某些权限只能是editor,换句话说，二级菜单某些只能管理员可见，某些只能普通用户可见。但是左侧菜单依然能看的到只能editor只见的菜单，并且能访问。请问这是bug吗？
![image](https://user-images.githubusercontent.com/31363817/86310523-e5618300-bc50-11ea-8c17-c988b42d5fa6.png)
已上图中的directive菜单管理员也能看到，其实只能普通用户可见。求解答

**Comment by mgbq** [comment]
admin是查看所有的
