### ISSUE TITLE
是借鉴pan神的？

### ISSUE THREAD

**Issue by moonose** [mgbq/vue-permission#9]
如果是借鉴潘神的 PanJiaChen/vue-element-admin， 记得提一下。

**Comment by daiing** [comment]
记得提一下

**Comment by aoilti** [comment]
+1

**Comment by mgbq** [comment]
有借鉴 [vueAdmin-template](https://github.com/PanJiaChen/vueAdmin-template),已经在readme标注

**Comment by liuhuiAndroid** [comment]
这不是有借鉴，简直是双胞胎啊。

**Comment by flywithbug** [comment]
哪里是借鉴，ReadME写在一个不起眼的角落，不知道的人还以为你写的呢。
还有里面的404页面比如 PanJiaChen 页面都会注明是华尔街见闻 来源，
你直接标注成自己的版权了。
 <div class="bullshit">
        <div class="bullshit__oops">OOPS!</div>
        <div class="bullshit__info">版权所有
          <a class='link-type' href='https://github.com/mgbq/nx-admin' target='_blank'>nxmin</a>
        </div>

不要太无耻。。。

**Comment by flywithbug** [comment]
还有，麻烦你的文档里，别把别人的技术当成自己原创， 还各种二维码要钱。。 真的太无耻了
